name: MysticCore
author: QuickScythe
version: 1.0.0
description: Runs on all MysticCloud servers
api-version: 1.15
main: net.mysticcloud.spigot.core.Main
commands:
  sql:
    usage: /sql [query]
    description: Run SQL commands from inside Minecraft!
  settings:
    usage: /settings
    description: Alter your settings.
  register:
    usage: /register <web name>
    description: Link your web Account and Minecraft account.
  pet:
    usage: /pet
    description: Summon a pet to follow you!
  debug:
    usage: /debug
    description: Toggles debug messages
  item:
    usage: /item <item> [player|all]
    description: Gives player a predefined custom item.
  grl:
    usage: /grl
    description: Kicks all players from the server while reloading. HyverseBungeeCore reconnects all kicked players after the reload is complete.
  kit:
    description: Main kits command.